dm fix.

diff --git a/desktop/xfce/base/xfce4-session/files/xinitrc.patch b/desktop/xfce/base/xfce4-session/files/xinitrc.patch
--- a/desktop/xfce/base/xfce4-session/files/xinitrc.patch
+++ b/desktop/xfce/base/xfce4-session/files/xinitrc.patch
@@ -1,19 +1,18 @@
---- a/scripts/xinitrc.in.in	2019-08-21 15:37:15.477003863 +0300
-+++ b/scripts/xinitrc.in.in	2019-08-21 17:33:08.702961360 +0300
-@@ -79,11 +79,13 @@
- test -r $HOME/.Xmodmap && xmodmap $HOME/.Xmodmap
- 
- # if XAUTHLOCALHOSTNAME is not set in systemd user session, starting of xfce4-notifyd, DISPLAY etc. will fail
--if command -v systemctl >/dev/null 2>&1 && systemctl --user list-jobs >/dev/null 2>&1; then # user session is running
--  dbus-update-activation-environment --systemd XAUTHLOCALHOSTNAME=$XAUTHLOCALHOSTNAME
-+#if command -v systemctl >/dev/null 2>&1 && systemctl --user list-jobs >/dev/null 2>&1; then # user session is running
-+#  dbus-update-activation-environment --systemd XAUTHLOCALHOSTNAME=$XAUTHLOCALHOSTNAME
-+#fi
-+if which dbus-update-activation-environment >/dev/null 2>/dev/null ; then
-+  dbus-update-activation-environment --systemd --all
+--- a/scripts/xinitrc.in.in	2019-10-16 17:00:56.364000642 +0300
++++ b/scripts/xinitrc.in.in	2019-10-16 17:03:41.612001128 +0300
+@@ -98,8 +98,13 @@
+     exit 1
+   fi
+ else
+-  # start xfce4-session normally
+-  exec xfce4-session
++  if [[ "$(pgrep -fu root 'autolaunch')" ]]; then
++    # start xfce4-session normally
++    exec xfce4-session
++  else
++    # hack for run session from sddm
++    exec dbus-launch --sh-syntax --exit-with-session xfce4-session
++  fi
  fi
  
--
- # check if we start xfce4-session with ck-launch-session. this is only
- # required for starting from a console, not a login manager
- if test "x$XFCE4_SESSION_WITH_CK" = "x1"; then
+ # if we got here, then exec failed
